source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FSCalendar', :exclusive => true do
  pod "FSCalendar", :path => "../"
  pod 'SSLunarDate'
end

target 'Tests', :exclusive => true do
  pod "FSCalendar", :path => "../"

  
end
